name: CI_ESlint
on: push

defaults:
  run:
    working-directory: ./web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - run: bun install
    - run: bun x eslint .
