name: CI_ESlint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: npm install
    - name: Run ESLint
      run: npm run eslint_src