name: CI_Jest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules and Test
      run: |
        npm add --dev jest
        npm add --dev lodash
        npm add --dev jest-environment-jsdom
        npm run test:js