name: CI_Jest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        yarn
        yarn add --dev jest
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: test_wgscovplot.js
