name: CI_Jest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules and Test
      run: |
        yarn
        yarn add --dev jest
        yarn add --dev lodash
        yarn run test:ci