name: Jest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: tests/test_wgscovplot.js
